import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

// Metadata for your app
export const metadata = {
  title: "AI Mockup Interview",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const clerkFrontendApi = process.env.NEXT_PUBLIC_CLERK_FRONTEND_API || "https://api.clerk.dev"; 

  return (
    <ClerkProvider frontendApi={clerkFrontendApi}>
      <html lang="en">
        <head>
          <link rel="icon" href="/ai.jpg" />
        </head>
        <body>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
