import { ClerkProvider, RedirectToSignIn, withServerSideAuth } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import ai from "../public/ai.jpg";
import { redirect } from "next/navigation"; // Import redirect

export const metadata = {
  title: "AI Mockup Interview",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const isAuthenticated = true; // Replace with actual auth check (e.g., Clerk)

  // Redirect user to the sign-in page if not authenticated
  if (!isAuthenticated) {
    redirect('/sign-in');
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="/ai.jpg" />
        </head>
        <body>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
